---
openapi: 3.0.0
info:
  title: Glovo menu API
  description: ''
  contact:
    email: rar.stas@gmail.com
  version: 1.0.0
tags:
- name: options
- name: products
paths:
  /options/:storeAddressId:
    get:
      tags:
      - options
      description: |
        get options by groups
      operationId: optionsGet
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OptionGroup'
    patch:
      tags:
      - options
      description: |
        edit options
      operationId: optionsPatch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OptionGroup'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OptionGroup'
        "204":
          description: No Content
        "422":
          description: Unprocessable Content
  /options/:storeAddressId/:groupId:
    delete:
      tags:
      - options
      description: |
        delete group of options.
      operationId: optionGroupDelete
      responses:
        "204":
          description: No Content
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OptionGroup'
  /options/:storeAddressId/:groupId/:optionId:
    delete:
      tags:
      - options
      description: |
        delete option by id.
      operationId: optionDelete
      responses:
        "204":
          description: No Content
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Option'
  /products/:storeAddressId:
    get:
      tags:
      - products
      description: |
        get products by groups
      operationId: productsGet
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductGroup'
    patch:
      tags:
      - products
      description: |
        edit product
      operationId: productsPatch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductGroup'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductGroup'
        "204":
          description: No Content
        "422":
          description: Unprocessable Content
  /products/:storeAddressId/:groupId:
    delete:
      tags:
      - products
      description: |
        delete group of products
      operationId: productGroupDelete
      responses:
        "204":
          description: No Content
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductGroup'
  /products/:storeAddressId/:groupId/:productId:
    delete:
      tags:
      - products
      description: |
        delete product by id
      operationId: productDelete
      responses:
        "204":
          description: No Content
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /menu-collections/:storeAddressId:
    get:
      tags:
        - collections
      description: |
        get collections
      operationId: CollectionsGet
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collections'
    patch:
      tags:
        - collections
      description: |
        edit collections
      operationId: collectionsPatch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Collections'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collections'
        "204":
          description: No Content
        "422":
          description: Unprocessable Content
  /menu-collections/:storeAddressId/:collectionId:
    delete:
      tags:
        - collections
      description: |
        delete menu-collection by id
      operationId: CollectionDelete
      responses:
        "204":
          description: No Content
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collections'
  /orders/status/:storeAddressId:
    put:
      tags:
        - orders
      description: |
        update order status
      operationId: orderUpdateStatus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                orderId:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: 'bad request'
components:
  schemas:
    Option:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        active:
          type: boolean
        price:
          type: number
      description: option for products
    OptionGroup:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        active:
          type: boolean
        min:
          type: number
        max:
          type: number
        moreThanOnce:
          type: boolean
        items:
          type: array
          items:
            $ref: '#/components/schemas/Option'
      description: group of options
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        active:
          type: boolean
        description:
          type: string
        price:
          type: number
        hitSales:
          type: boolean
        image:
          type: string
        position:
          type: integer
        options:
          type: array
          items:
            type: string
          description: array id options
      description: product
    ProductGroup:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        active:
          type: boolean
        position:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
      description: group of products
    Collections:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        active:
          type: boolean
        position:
          type: integer
        image:
          type: string
        productGroups:
          type: array
          items:
            type: string
          description: array id of ProductGroups

      description: Collection list
    Order:
      type: object
      properties:
        order_id:
          type: string
        store_id:
          type: string
        order_time:
          type: string
        estimated_pickup_time:
          type: string
        utc_offset_minutes:
          type: string
        payment_method:
          type: string
        currency:
          type: string
        order_code:
          type: string
        allergy_info:
          type: string
        special_requirements:
          type: string
        estimated_total_price:
          type: number
        delivery_fee:
          type: integer
        minimum_basket_surcharge:
          type: integer
        customer_cash_payment_amount:
          type: integer
        courier:
          type: object
          properties:
            name:
              type: string
            phone_number:
              type: string
        customer:
          type: object
          properties:
            name:
              type: string
            hash:
              type: string
            invoicing_details:
              type: object
              properties:
                company_name:
                  type: string
                company_address:
                  type: string
                tax_id:
                  type: string
        product:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              purchased_product_id:
                type: string
              name:
                type: string
              price:
                type: number
              quantity:
                type: integer
              attributes:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
                    quantity:
                      type: integer
        delivery_address:
          type: object
          properties:
            label:
              type: string
            latitude:
              type: number
            longitude:
              type: number
        bundled_orders:
          type: array
          items:
            type: string
        pick_up_code:
          type: string
        is_picked_up_by_customer:
          type: boolean
        cutlery_requested:
          type: boolean
        partner_discounts_products:
          type: integer
        partner_discounted_products_total:
          type: integer
        total_customer_to_pay:
          type: integer
        loyalty_card:
          type: string
      description: Order object
    OrderCancelled:
      type: object
      properties:
        order_id:
          type: string
        store_id:
          type: string
        cancel_reason:
          type: string
        payment_strategy:
          type: string
      description: Order cancelled object

